// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * M6：设置页返回给前端的应用设置（root + autostart）。
 */
export type AppSettings = { 
/**
 * 当前数据根目录（绝对路径）。
 */
root: string, 
/**
 * 开机自启是否开启（运行时读注册表，不入 settings.json）。
 */
autostart: boolean, };

/**
 * `assets_import` 返回结果（M3-3）：图片在根内的相对引用 + 该笔记新图片总数。
 */
export type AssetImport = { 
/**
 * 图片相对根目录路径（`/` 分隔），如 `收件箱/note/assets/note-1.png`。
 */
rel: string, 
/**
 * 导入后该笔记 `assets/` 下的图片总数。
 */
count: number, };

export type NoteFormat = "md" | "txt";

export type NoteMeta = { 
/**
 * 相对路径的稳定哈希（十六进制），作为前端 key。
 */
id: string, 
/**
 * frontmatter title，无则取文件名。
 */
title: string, 
/**
 * 相对根目录路径（`/` 分隔）。
 */
path: string, format: NoteFormat, 
/**
 * 最后修改时间（Unix 毫秒）。
 */
mtime: number, imageCount: number, tags: Array<string>, pinned: boolean, 
/**
 * 正文首行截断 80 字。
 */
preview: string, 
/**
 * 正文前 500 字，供前端倒排索引（M2 搜索）。
 */
searchText: string, };
